###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: '3.1'
services:
#    mailhog:
#        image: 'mailhog/mailhog:latest'
#        ports:
#            - '5556:8025'

#    redis:
#        image: 'redis:alpine'

    mysql:
        image: 'mysql:8.0'
        working_dir: /app
        volumes:
            - '.:/app'
        environment:
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_DATABASE=news
            - MYSQL_USER=user
            - MYSQL_PASSWORD=password
        ports:
            - '5557:3306'

    webserver:
        image: 'nginx:alpine'
        working_dir: /app
        volumes:
            - '.:/app'
            - './phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
            - './phpdocker/nginx/certs/localhost.crt:/etc/nginx/localhost.crt'
            - './phpdocker/nginx/certs/localhost.key:/etc/nginx/localhost.key'
        ports:
            - '80:80'
            - '443:443'

    php-fpm:
        build: phpdocker/php-fpm
        working_dir: /app
        volumes:
            - '.:/app'
            - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.2/fpm/conf.d/99-overrides.ini'
